build(release): update release scripts

diff --git a/bin/release/prerelease b/bin/release/prerelease
--- a/bin/release/prerelease
+++ b/bin/release/prerelease
@@ -1,26 +1,42 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-# declare path to this script
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"
+REQUIRED_TOOLS=(
+  git
+  hugo
+  typos
+)
 
-# update repository files
-./bin/dnb-update-repofiles.sh
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
 
-# TODO read component names into array
-# TODO read replacement configuration into array
+SCRIPTPATH="$(
+   cd "$(dirname "$0")" >/dev/null 2>&1 || exit
+   pwd -P
+)"
+CURPATH="$(pwd -P)"
 
-# remove replacement scripts
+typos -- ./content
+
 if test -f "$SCRIPTPATH"/replacements; then
   while read -ra __; do
     go mod edit -dropreplace "${__[0]}"
   done < "$SCRIPTPATH"/replacements
 fi
 
+"${CURPATH}"/bin/build/prepare-docs
+
 hugo mod get -u ./...
 hugo mod tidy
 
-git add go.mod
-git add go.sum
+git add "${CURPATH}"/go.mod
+FILE="${CURPATH}"/go.sum
+if test -f "$FILE"; then
+    git add go.sum
+fi
 
 if test -f "$SCRIPTPATH"/replacements; then
   while read -ra __; do
